### ISSUE TITLE
Adicionar o comando de lixeira

### ISSUE THREAD

**Issue by MrPowerGamerBR** [PerfectDreams/StickyNotes#1]
As vezes é difícil encontrar um lugar legal para jogar as coisas foras, jogar no chão prejudica o TPS do servidor e ainda por cima cria uma bagunça no chão.

Jogar na lava é bom, mas as vezes é chato ficar procurando lava para jogar as coisas foras.

**Comment by MrGaabriel** [comment]
https://github.com/PerfectDreams/DreamMini/commit/a5c85fe2be38eb3c4cec01fbda031f70ff4b83b0
