### ISSUE TITLE
Fazer a Pantufa assinar uma casa (ou até mesmo o SparklyBot).

### ISSUE THREAD

**Issue by BsouzaM** [PerfectDreams/StickyNotes#11]
## 🤔 Antes de enviar...
Para manter tudo organizado, siga estes passos antes de começar:
- [X] Eu já confirmei que esta sugestão será útil para outros usuários.
- [X] Eu já procurei por sugestões parecidas no repositório.
- [X] Eu já verifiquei que não existe nenhuma outra branch ou pull request aberto com a minha sugestão ou com uma sugestão parecida.
- [ ] Eu tentei procurar por [outros repositórios do PerfectDreams](https://github.com/PerfectDreams) um repositório relacionado com a minha sugestão, mas não encontrei/é uma sugestão sobre algo que não tem nada relacionado no servidor.

### 🎮 Seu nome no PerfectDreams
KneezMz

### ✨ Descrição da sugestão
Fazer a pantufa (ou o famosíssimo e falido SparklyBot) assinar as casas das pessoas;

[Assina minha casa? :)](https://i.imgur.com/O5LuPvq.png)

### 🌟 Como irá funcionar?
Quando um player fala no chat: "Assina minha casa", os bots (Pantufa ou SparklyBot) teleportam-se para o player, um deles deixa uma plaquinha assinada na posição onde o player está (a posição da placa varia de acordo com a rotação do player) e some.

### 😎 Porque ela seria legal no PerfectDreams?
Porque isso traz a nostalgia de jogar no SparklyPower. Aposto que muitas pessoas que jogavam lá também sentem a saudade de ver isso novamente.

### 🍃 Qualquer outra coisa
[Nunca é um adeus](https://imgur.com/a/hp0ROZl)

**Comment by MrPowerGamerBR** [comment]
Já está implementado
