### ISSUE TITLE
Sistema do Casino para o Perfect Dreams.

### ISSUE THREAD

**Issue by BsouzaM** [PerfectDreams/StickyNotes#12]
## 🤔 Antes de enviar...
Para manter tudo organizado, siga estes passos antes de começar:
- [X] Eu já confirmei que esta sugestão será útil para outros usuários.
- [X] Eu já procurei por sugestões parecidas no repositório.
- [X] Eu já verifiquei que não existe nenhuma outra branch ou pull request aberto com a minha sugestão ou com uma sugestão parecida.
- [ ] Eu tentei procurar por [outros repositórios do PerfectDreams](https://github.com/PerfectDreams) um repositório relacionado com a minha sugestão, mas não encontrei/é uma sugestão sobre algo que não tem nada relacionado no servidor.

### 🎮 Seu nome no PerfectDreams
KneezMz

### ✨ Descrição da sugestão
A sugestão chama-se Casino. Seria uma forma mais adapatada do casino antigo do SparklyPower.

### 🌟 Como irá funcionar?
A ideia seria utilizar custom items que se ganham na tela do casino. Vamos pegar por exemplo o item Clay (não o bloco). O Clay se chama C1 (um custom item utilizável), o significado de C1 é CASINO 1, e o C1 vale 300 Sonhos (por exemplo), ao jogar, o player terá uma ficha para usar no casino, usando a ficha aparecerá a tela onde os Clays (de cores diferentes) irão passar na tela. Existem vários "C"s do casino, variam de C1 a C9, pois são 9 espaços que aparecem na tela do casino. C1 vale X sonhos, enquanto o C9 vale muito mais que todos os outros. Ao ter esse C1, C2, etc. o player deverá clicar com o botão direito para usar, resultando que ele ganha o dinheiro.

[Exemplo de um bom layout de casino](https://i.imgur.com/Od59QBu.png)

### 😎 Porque ela seria legal no PerfectDreams?
Porque ajuda com a economia do servidor e você pode variar a quantidade de sonhos ganhos em cada "C" para se adaptar a economia correta.

**Comment by MrPowerGamerBR** [comment]
Já está implementado com um sistema de placas, e eu acho que com placas é melhor porque dá para ver os outros jogadores apostando dinheiro (e normalmente perdendo)
