### ISSUE TITLE
Sistema de Jornal do Perfect Dreams

### ISSUE THREAD

**Issue by BsouzaM** [PerfectDreams/StickyNotes#17]
## 🤔 Antes de enviar...
Para manter tudo organizado, siga estes passos antes de começar:
- [X] Eu já confirmei que esta sugestão será útil para outros usuários.
- [x] Eu já procurei por sugestões parecidas no repositório.
- [ ] Eu já verifiquei que não existe nenhuma outra branch ou pull request aberto com a minha sugestão ou com uma sugestão parecida.
- [ ] Eu tentei procurar por [outros repositórios do PerfectDreams](https://github.com/PerfectDreams) um repositório relacionado com a minha sugestão, mas não encontrei/é uma sugestão sobre algo que não tem nada relacionado no servidor.

### 🎮 Seu nome no PerfectDreams
KneezMz

### ✨ Descrição da sugestão
A sugestão é sobre o Newsletter do PerfectDreams, para atualizar os players!

### 🌟 Como irá funcionar?
Já imaginou um simples papel (feito com cana de açúcar) ser um jornal que você recebe todos os dias (ou um dia específico) com todas as atualizações sobre o PerfectDreams ou até mesmo da Loritta? Pois bem. 

**É aqui que eu explico:** Eu acho que seria chato pois não quero ficar recebendo isso toda hora. É para isso que serve as opções. No jornal você escolhe se quer receber as mais novas atualizações do PerfectDreams, do PerfectDreams e da Loritta, só da Loritta ou nenhum dos dois. É literalmente um newsletter do PerfectDreams(TM). O newsletter do PerfectDreams é como um mapa que vêm para o seu inventário com as notícias do dia, ou simplesmente um newsletter utilizável com o botão direito, para que assim apareça no chat quais são as novidades do dia. Como o jornal é algo do dia, então existem outros jornais para outros dias. Mas e se esse jornal utilizável com o botão direito pudesse ver o histórico dos outros dias?

### 😎 Porque ela seria legal no PerfectDreams?
Seria legal para manter os players atualizados do que acontece no PerfectDreams ao invés de ter que ficar vendo o Discord ou o Github para saber o que mudou.

**Comment by MrPowerGamerBR** [comment]
#6
