### ISSUE TITLE
Objetivos globais

### ISSUE THREAD

**Issue by FlammDumbFox** [PerfectDreams/StickyNotes#29]
## 🤔 Antes de enviar...
Para manter tudo organizado, siga estes passos antes de começar:
- [ ] Eu já confirmei que esta sugestão será útil para outros usuários.
- [x] Eu já procurei por sugestões parecidas no repositório.
- [x] Eu já verifiquei que não existe nenhuma outra branch ou pull request aberto com a minha sugestão ou com uma sugestão parecida.
- [ ] Eu tentei procurar por [outros repositórios do PerfectDreams](https://github.com/PerfectDreams) um repositório relacionado com a minha sugestão, mas não encontrei/é uma sugestão sobre algo que não tem nada relacionado no servidor.

### 🎮 Seu nome no PerfectDreams
Flamm

### ✨ Descrição da sugestão
Adiciona objetivos nos quais todos os jogadores poderão trabalhar, dando recompensas para os 10 jogadores que mais contribuírem.

### 🌟 Como irá funcionar?
Assim que um determinado número de jogadores entrar, o primeiro objetivo global é lançado.

No momento em que esse for completado, um objetivo deve ser trocado por outro aleatoriamente escolhido e os 10 jogadores que mais colaborarem devem ser recompensados de alguma forma. Uma sugestão seria distribuir uma quantidade P de dinheiro proporcionalmente à contribuição de cada jogador no top 10 de contribuição. Outra seria dividir uma porcentagem para o primeiro colocado, outra para os segundo e terceiro e uma menor para os demais.

O valor de P pode ser definido aleatoriamente ou ser ajustado de acordo com a dificuldade do objetivo.

Comando: **/objetivo(s)**
Função: mostra o objetivo atual e uma lista com os 10 jogadores que mais colaboraram até a última atualização do ranking.

Caso haja um argumento `rank(ing)/top/ladder`, deve ser mostrado uma tabela que mostre os 5 jogadores que mais vezes ficaram no top 10.

Caso haja um argumento `stats/info player`, devem ser mostradas a quantidade de primeira colocação e quantidade de vezes que `player` esteve no top 10.

Sugestões de objetivos globais:
- Coleta: *quebre uma determinada quantidade de <material>*
  - Pedra (incluindo os de metadata != 0)
  - Madeira (incluindo os de metadata != 0)
  - Minério de <qualquer coisa>
  - ...
- Eliminação: *derrote uma determinada quantidade de <monstro>*
  - Creeper
  - Zumbi
  - ...
- Servidor: *colabore com outros jogadores para atingir uma determinada quantidade de <sei lá>*
  - Votos
  - Participações em eventos
  - ...
- ...
### 😎 Porque ela seria legal no PerfectDreams?
É mais uma outra forma de aumentar a retenção dos players, recompensando aqueles que mais ajudarem a completar determinado objetivo. 

Caso os achievements sejam implementados, alguns dos achievements podem estar relacionados a esse sistema, como, por exemplo:

Achievement: **Quase lá!**
Flavor text: *Já consigo ver a luz do Sol no penúltimo degrau.*
Método de obtenção: obtenha segundo lugar no ranking de contribuição.

Achievement: **Competição?**
Flavor text: *Quando você é um e apenas um basta...*
Método de obtenção: contribua, sozinho, para 25% (50% é muito, não?) do objetivo.

Achievement: **Colaborador Iniciante**
Flavor text: *A primeira!*
Método de obtenção: fique uma vez no primeiro lugar no ranking de contribuição.

[...]

Achievement; **Colaborador Mestre**
Flavor text: *Quando é possível tocar os céus, novos horizontes se abrem.*
Método de obtenção: fique 100 vezes no primeiro lugar do ranking de contribuição.

Caso sejam implementadas as Tags, esse achievement também poderá dar, ao usuário, uma tag diferenciada.

### 🍃 Qualquer outra coisa
🦊

**Comment by Pokeer** [comment]
Dá pra jogar os objetivos que estão acontecendo no leaderboard

**Comment by MrPowerGamerBR** [comment]
Acho que seria uma duplicata de #14, melhor enviar todas essas ideias lá.
